/*
 * Port_PBCFG.c
 *
 *  Created on: Nov 22, 2023
 *      Author: Nour El Dein Hany
 */
#include"Port.h"
/*
 * Module Version 1.0.0
 */
#define Port_PBCFG_SW_MAJOR_VERSION              (1U)
#define Port_PBCFG_SW_MINOR_VERSION              (0U)
#define Port_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define Port_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define Port_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define Port_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((Port_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
		||  (Port_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
		||  (Port_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((Port_PBCFG_SW_MAJOR_VERSION != Port_SW_MAJOR_VERSION)\
		||  (Port_PBCFG_SW_MINOR_VERSION != Port_SW_MINOR_VERSION)\
		||  (Port_PBCFG_SW_PATCH_VERSION != Port_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
 /*
  *Pin0 >>>>>>>>
  *Pin0 PA0
 * Pin1 >>>>>>>>  PA1
 * Pin2 >>>>>>>>  PA2
 * Pin3 >>>>>>>>  PA3
 * Pin4 >>>>>>>>  PA4
 * Pin5 >>>>>>>>  PA5
 * Pin6 >>>>>>>>  PA6
 * Pin7 >>>>>>>>  PA7
 * Pin8 >>>>>>>>  PA8
 * Pin9 >>>>>>>>  PA9
 * Pin10 >>>>>>>> PA10
 * Pin11 >>>>>>>> PA11
 * Pin12 >>>>>>>> PA12
 * Pin13 >>>>>>>> PA13
 * Pin14 >>>>>>>> PA14
 * Pin15 >>>>>>>> PA15
 * Pin16 >>>>>>>> PB0
 * Pin17 >>>>>>>> PB1
 * Pin18 >>>>>>>> PB2
 * Pin19 >>>>>>>> PB3
 * Pin20 >>>>>>>> PB4
 * Pin21 >>>>>>>> PB5
 * Pin22 >>>>>>>> PB6
 * Pin23 >>>>>>>> PB7
 * Pin24 >>>>>>>> PB8
 * Pin25 >>>>>>>> PB9
 * Pin26 >>>>>>>> PB10
 * Pin27 >>>>>>>> PB11
 * Pin28 >>>>>>>> PB12
 * Pin29 >>>>>>>> PB13
 * Pin30 >>>>>>>> PB14
 * Pin31 >>>>>>>> PB15
 *
 * */
 const Port_ConfigType Port_Configuration[NUM_OF_PINS]=
	{
			{GPIO_PORTA ,PORT_PIN_0,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_1,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_LOW, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_2,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_3,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_4,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_5,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_6,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_7,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_8,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_9,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_10,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_LOW, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_11,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_12,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_13,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_14,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTA ,PORT_PIN_15,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},

			{GPIO_PORTB ,PORT_PIN_16,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_17,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_18,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_19,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_20,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_21,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_22,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_23,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_24,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_25,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_26,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_27,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_28,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_29,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_30,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON},
			{GPIO_PORTB ,PORT_PIN_31,  PORT_PIN_OUT, GPIO_PIN_DIO_MODE ,STD_HIGH, STD_ON, STD_ON}


	};
